logs:
  - name: root
    level: INFO
    type: async
    async_unsafe: false
    pattern: "[%d{%Y-%m-%d %H:%M:%S}][%p][%f:%l]%m%n"
    appenders:
      - type: StdoutLogAppender
      - type: RollByTimeLogAppender
        dir: /home/zch/Project/zchlog/logs
        gap: day

  - name: zchlog
    level: DEBUG
    type: sync
    appenders:
      - type: FileLogAppender
        file: /home/zch/Project/zchlog/logs/zchlog.log
